define({
    //#region Rota
    rota: {
        createduser: 'Created User',
        createddate: 'Created Date',
        modifieduser: 'Modified User',
        modifieddate: 'Modified Date',
        urlparametrebilgi: "To give default value to parameters,you can add your value next to parameter such as '{parametren}' .e.g:Example/:id{1}",
        duzeltiliyor: 'Editing',
        zorunlualanlarvar: 'Please type in mandotary missing fields !',
        evet: 'Yes',
        hayir: 'No',
        disariyaaktar: 'Export',
        aktarallcsv: 'All data .csv',
        aktarekrandakicsv: 'Visible data .csv',
        aktarsecilicsv: 'Selected data .csv',
        aktarallpdf: 'All data .pdf',
        aktarekrandakipdf: 'Visible data .pdf',
        aktarsecilipdf: 'Selected data .pdf',
        sayfa: 'Page',
        toplam: 'Total',
        son: 'Last',
        ilk: 'First',
        yeni: 'New',
        yenikopyala: 'Copy this item',
        kayitkopyalandı: 'Item succesfully copied',
        sonrakikayit: 'Next',
        oncekikayit: 'Prev',
        yenikayit: 'New Record',
        kayitduzeltme: 'Update Record',
        ara: 'Search',
        temizle: 'Clear',
        crudonay: 'Do you want to save the changes ?',
        tt_bironcekisayfayadon: 'Go to previous page',
        tt_kaydet: 'Save all changes',
        tt_kaydetdevam: 'Save all changes and continue ',
        tt_gerial: 'Revert back all changes',
        tt_sil: 'Delete the record',
        gonder: 'Send',
        tt_dosyasecmekicintiklayiniz: 'Click to choose a file',
        dosyaseciniz: 'Choose a file',
        iptal: 'Cancel',
        bugun: 'Today',
        sonbirhafta: 'Last 1 week',
        sonbiray: 'Last 1 month',
        sonaltiay: 'Last 6 month',
        sonbiryil: 'Last 1 year',
        ozel: 'Custom',
        cikisonay: 'Are you sure to exit ?',
        filter: 'Filter Criters',
        ayarlar: 'Options',
        genislet: 'Expand',
        daralt: 'Collapse',
        filtreyitemizle: 'Clear filter',
        kayitsilindi: 'Item removed',
        kayiteklendi: 'Item added',
        tumkayitlarsilindi: 'All items removed',
        tumkayitlareklendi: 'All items added',
        zatenekli: 'Item Already added !',
        onaytumkayitekle: 'All items will be added.Are you sure to continue ?',
        onaytumkayitsil: 'All items will be deleted.Are you sure to continue ?',
        tumunuekle: 'Add all items',
        tumunusil: 'Remove all items',
        kayitsayisi: 'Line count',
        kayitbulunamadi: 'No record found',
        close: "Close",
        prev: 'Prev',
        next: 'Next',
        first: 'First',
        last: 'Last',
        kaydetdevam: 'Save & Continue',
        succesfullyprocessed: 'Succesfully processed !',
        titleinfo: 'Info',
        titleerror: 'Error',
        titlewarn: 'Warning',
        onay: "Confirm",
        titlesuccess: 'Success',
        titledebug:'Debug',
        seciniz: "Choose Item..",
        required_validator_messagetemplate: "'%displayName%' field is mandatory.",
        email_validator_messagetemplate: "'%displayName%' not valid email address",
        yenile: "Refresh",
        geridon: "Go Back",
        sil: "Delete",
        detay: "Detail",
        tamam: 'OK',
        ekle: "Add",
        guncelle: "Update",
        kaydet: "Save",
        gerial: "Revert Back",
        ok: "OK",
        deleteconfirmtitle: "Delete Confirm",
        deleteconfirm: "Are you sure to delete the record ?",
        login: "Login",
        signIn: "Sign In",
        cancel: "Cancel",
        username: "User Name",
        password: "Password",
        rememberme: "Remember me",
        unauthorized: "You are not authorized to view this page !",
        invalidfiletypemessage: "Only {0} file types are allowed to upload.<b><i>{1}</i></b> file has been ignored.",
        lutfenbekleyiniz: "Please wait...",
        durum: "State",
        error404description: "The page you requested could not be found, either contact your webmaster or try again. Use your browsers Back button to navigate to the page you have prevously come from",
        aktifmi: "Active ?",
        yetkihatasiaciklama: "You are not authorized to perform this action !",
        yetkihatasi: "Authorization Failed",
        validationhatasi: "Validation Failed",
        hata: 'Error',
        yenidenbaslat: 'Restart !',
        hataolustu: 'An error occured !',
        hataozur: 'Apologize for inconvenience situation.We have been informed about the exception.We will fix it soon.',
        hataaciklama: 'Error description :',
        secilikayit: 'Selected {0}',
        modelbulunamadi: 'The item you are looking for either was removed or you have insufficent permission to see.<b>\'New Record\'</b> mode active!'
    }
    //#endregion
});