define({
    rota: {
        createduser: 'Yaratan Kull.',
        createddate: 'Yaratma Tarihi',
        modifieduser: 'Güncelleyen Kull.',
        modifieddate: 'Güncelleme Tarihi',
        urlparametrebilgi: "Url parametrelerine varsayilan deger atamak için '{parametren}' şeklinde tanımlama yapabilirsiniz.Örn:Deneme/:id{1}",
        duzeltiliyor: 'Düzeltilyor',
        zorunlualanlarvar: 'Zorunlu alanları doldurunuz !',
        evet: 'Evet',
        hayir: 'Hayır',
        disariyaaktar: 'Dışarıya Aktar',
        aktarallcsv: 'Tüm data .csv',
        aktarekrandakicsv: 'Ekrandaki data .csv',
        aktarsecilicsv: 'Seçili data .csv',
        aktarallpdf: 'Tüm data .pdf',
        aktarekrandakipdf: 'Ekrandaki data .pdf',
        aktarsecilipdf: 'Seçili data .pdf',
        sayfa: 'Sayfa',
        toplam: 'Toplam',
        son: 'Son',
        ilk: 'İlk',
        yeni: 'Yeni',
        yenikopyala: 'Kaydı kopyala',
        kayitkopyalandı: 'Kayıt başarıyla kopyalandı',
        sonrakikayit: 'Sonraki',
        oncekikayit: 'Önceki',
        yenikayit: 'Yeni Kayıt',
        kayitduzeltme: 'Kayıt Düzeltme',
        ara: 'Ara',
        temizle: 'Temizle',
        crudonay: 'Yaptıgınız değişiklikleri kayit etmek istiyormusunuz ?',
        tt_bironcekisayfayadon: 'Bir önceki sayfaya gider',
        tt_kaydet: 'Yapılan değişikliklari kayit eder',
        tt_kaydetdevam: 'Değişklikleri kaydedip yeni kayıt açar',
        tt_gerial: 'Yapılan değişiklikleri geri alır',
        tt_sil: 'Kaydı siler',
        gonder: 'Gönder',
        tt_dosyasecmekicintiklayiniz: 'Dosya seçmek için tıklayınız',
        dosyaseciniz: 'Dosya seçiniz...',
        iptal: 'İptal',
        bugun: 'Bugün',
        sonbirhafta: 'Son 1 hafta',
        sonbiray: 'Son 1 ay',
        sonaltiay: 'Son 6 ay',
        sonbiryil: 'Son 1 yil',
        ozel: 'Özel',
        cikisonay: 'Çıkmak istediğinize eminmisiniz ?',
        filter: 'Filtre Kriterleri',
        ayarlar: 'Ayarlar',
        genislet: 'Genişlet',
        daralt: 'Daralt',
        filtreyitemizle: 'Filtreyi temizle',
        kayitsilindi: 'Kayıt silindi',
        kayiteklendi: 'Kayıt eklendi',
        tumkayitlarsilindi: 'Tüm kayıtlar silindi',
        tumkayitlareklendi: 'Tüm kayıtlar eklendi',
        zatenekli: 'Kayıt zaten ekli !',
        onay: 'Onay',
        onaytumkayitekle: 'Tüm kayıtlar eklenecek devam etmek istiyormusunuz ?',
        onaytumkayitsil: 'Tüm kayıtlar silinecek devam etmek istiyormusunuz ?',
        tumunuekle: 'Tüm kayıtları ekle',
        tumunusil: 'Tüm kayıtları sil',
        kayitsayisi: 'Kayit sayısı',
        kayitbulunamadi: 'Kayıt bulunamadı',
        close: "Kapat",
        prev: 'Önceki',
        next: 'Sonraki',
        first: 'İlk',
        last: 'Son',
        kaydetdevam: 'Kaydet & Devam',
        succesfullyprocessed: 'İşlem başarıyla tamamlanmıştır!',
        titleinfo: 'Bilgi',
        titleerror: 'Hata',
        titlewarn: 'Uyarı',
        titlesuccess: 'Başarılı',
        titledebug: 'Debug',
        seciniz: "Seçim Yapınız..",
        required_validator_messagetemplate: "'%displayName%' girilmesi zorunlu alandır",
        email_validator_messagetemplate: "'%displayName%' geçersiz email adresi",
        yenile: "Yenile",
        geridon: "Geri",
        sil: "Sil",
        Detay: "Detay",
        tamam: 'Tamam',
        ekle: "Ekle",
        guncelle: "Güncelle",
        kaydet: "Kaydet",
        gerial: "Geri Al",
        ok: "Tamam",
        deleteconfirmtitle: "Silme Onayı",
        deleteconfirm: "Kaydı silmek istediğinize eminmisiniz ?",
        unauthorized: "Bu formu görmeye yetkiniz yok !",
        invalidfiletypemessage: "Sadece {0} uzantılı dosyaları yükleyebilirsiniz.<b><i>{1}</i></b> dosyasının yüklemesi iptal oldu !",
        lutfenbekleyiniz: "Lütfen bekleyiniz...",
        durum: "Durum",
        sayfabulunamadi: "Sayfa Bulunamadı",
        error404description: "Aradığınız sayfa bulunamadı,sistem yöneticisi ile görüşün veya tekrar deneyin.Browserin geri tuşunu kullanarak bir önceki sayfaya dönebilirsiniz.",
        aktifmi: "Aktif mi?",
        yetkihatasiaciklama: "Bu işlemi yapmaya yetkiniz yok!",
        yetkihatasi: "Yetki Hatası",
        validationhatasi: "Eksik & Hatalı Alan !",
        hata: 'Hata',
        yenidenbaslat: 'Yeniden başlat !',
        hataolustu: 'Uygulamada hata oluştu !',
        hataozur: 'Oluşan hata yüzünden özür dileriz,hata ile ilgili bilgiler sistemimize kayit edildi.En yakın zamanda sorunu çözeceğiz.',
        hataaciklama: 'Hata detayi :',
        secilikayit: 'Seçili {0}',
        modelbulunamadi: 'Aradığınız kayıt silinmiş veya görme yetkiniz yok.<b>\'Yeni kayıt\'</b> moduna geçildi!'
    }
});